language: python
python:
  - 3.5
  - &mainstream_python 3.6
  - 3.6-dev
  - 3.7-dev
cache: pip
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
script:
  - python -m pytest -v
